spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: 'TRUE'
        hibernate:
            ddl-auto: update
        open-in-view: 'false'
    mvc:
        hiddenmethod:
            filter:
                enabled: 'true'
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
#        username: root
#        password: 1234
        username: qnb9ld8aqehd0yw1
        password: wsfuug8fkhz91bga
#        url: jdbc:mysql://localhost:3306/modern_kids?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        url: jdbc:mysql://zj2x67aktl2o6q2n.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/iv5jhkytlw947w22?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    logging:
        level:
            org:
                hibernate:
                    type:
                        descriptor: TRACE
                    SQL: DEBUG
                nodeValue: WARN
            blog: WARN
server:
#    port: 8080
    port: ${PORT:8080}
stripe:
    api:
        publicKey: pk_test_51PCQyQK1okK6WvpRPBUAmf6gISNlFwG5Yfpv580f6Y5lLbEPR5qxDc4cDUqCZb8DXxWVPdryKLdF2wVZkq14z01w000IWS0tfV
        secretKey: sk_test_51PCQyQK1okK6WvpRq92LEyKJ5mJpIjcLFgj0b0D0tUgNotFFGBbzoCsLpB5mWUMQfXYKNTt61qga0kTEPBHLyyUn00gGBNaYUc

