name: Build_Test_Debloy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_unit-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js 21.x
      uses: actions/setup-node@v3
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Diplay softuni username
      run: echo "Stasi03"
